spring:
  application:
    name: hexletTypoReporter
  profiles:
    active: dev
  security:
    require-ssl: false
    oauth2:
      client:
        registration:
          vk:
            client-id: ${VK_CLIENT_ID}
            client-secret: ${VK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/vk"
            scope: email
            client-name: VK
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?fields=email,first_name,last_name,photo_200
            user-name-attribute: login
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    problemdetails:
      enabled: true

